global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "otel-collector"
    static_configs:
      - targets: [ "otel-collector:9464" ]

  - job_name: "reactive-books-service"
    metrics_path: "/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8080" ]